import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gaadi Ghoda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-4xl font-medium text-center my-20">Home Page</p>
        <div className="relative w-full max-w-md h-96 mx-auto">
          <Image
            src="https://cdn1.vectorstock.com/i/1000x1000/95/15/great-horse-car-vector-15439515.jpg"
            layout="fill"
            objectFit="contain"
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
