import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useForm } from 'react-hook-form';
import { FiSend } from 'react-icons/fi';
import Button from '../components/Button';
import ControlledTextField from '../components/form/ControlledTextField';

const Home: NextPage = () => {
  const { control, handleSubmit } = useForm();
  const onSubmit = (values: any) => {
    console.log('[FormValues]', values);
  };

  return (
    <div>
      <Head>
        <title>Gaadi Ghoda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-4xl font-medium text-center my-20">Home Page</p>
        <div className="relative w-full max-w-md h-96 mx-auto">
          <Image
            src="https://cdn1.vectorstock.com/i/1000x1000/95/15/great-horse-car-vector-15439515.jpg"
            layout="fill"
            objectFit="contain"
          />
        </div>
      </main>
      <form
        className="my-10 flex flex-col items-center gap-2"
        onSubmit={handleSubmit(onSubmit)}
      >
        <ControlledTextField
          control={control}
          name="username"
          label="Username"
          rightIcon={<FiSend />}
          rules={{ required: 'Required', min: 6 }}
        />
        <Button
          label="Submit"
          type="submit"
          leftIcon={<FiSend />}
          rightIcon={<FiSend />}
        />
      </form>
    </div>
  );
};

export default Home;
